server:
  port: 8090

spring:
  datasource:
    druid:
      stat-view-servlet:
        enabled: true
        loginUsername: admin
        loginPassword: 123456
        allow:
      web-stat-filter:
        enabled: true
    type: com.alibaba.druid.pool.DruidDataSource
    sqlite01:
      url: jdbc:sqlite:D:/test_1.pak
      username:
      password:
      driver-class-name: org.sqlite.JDBC


#mybatis-plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #开启SQL语句打印 输出日志文件中
  mapper-locations: classpath:mapper/*.xml    #mapper.xml 文件位置解决单独编写SQL问题
terrain:
  sqlite:
    directory: D:\
logging:
  level:
    com.wonders.*: debug